Using Numpy Library functions 

In [1]:
import numpy as np

In [ ]:

scores = np.array([
[1,95,99,85,78,93], # Student 1
[2,97,80,75,68,83], # Student 2
[3,45,99,65,98,63], # Student 3
[4,65,59,89,68,93], # Student 4
[5,55,49,83,70,63], # Student 5
[6,85,39,50,78,91]  # Student 6
])

print("********** Students Exam Score Analysis **********")
print(scores)

********** Students Exam Score Analysis **********
[[ 1 95 99 85 78 93]
 [ 2 97 80 75 68 83]
 [ 3 45 99 65 98 63]
 [ 4 65 59 89 68 93]
 [ 5 55 49 83 70 63]
 [ 6 85 39 50 78 91]]


In [3]:
# Average of score
avg =  np.mean(scores[:6],axis=1)
print("Average Of Score: ",avg )

# Minimum score
min_score = np.min(scores[:,1 :],axis=1)
print("Minimum score: ",min_score)

# Maximum Score
max_score = np.max(scores[:,1 :],axis=1)
print("Maximum score: ",max_score)

# cummilative score
cummilative_score = np.cumsum(scores[:, 1:],axis=1)
print("cumsum: " ,cummilative_score)


# total for each row
total = np.sum(scores[:, 1:],axis=1)
print("Total:" ,total)





Average Of Score:  [75.16666667 67.5        62.16666667 63.         54.16666667 58.16666667]
Minimum score:  [78 68 45 59 49 39]
Maximum score:  [99 97 99 93 83 91]
cumsum:  [[ 95 194 279 357 450]
 [ 97 177 252 320 403]
 [ 45 144 209 307 370]
 [ 65 124 213 281 374]
 [ 55 104 187 257 320]
 [ 85 124 174 252 343]]
Total: [450 403 370 374 320 343]


In [10]:
pow = np.power(scores,2)
print(pow)

sorted_score = np.sort(scores)
print("Sorted Score: ",sorted_score)


[[   1 9025 9801 7225 6084 8649]
 [   4 9409 6400 5625 4624 6889]
 [   9 2025 9801 4225 9604 3969]
 [  16 4225 3481 7921 4624 8649]
 [  25 3025 2401 6889 4900 3969]
 [  36 7225 1521 2500 6084 8281]]
Sorted Score:  [[ 1 78 85 93 95 99]
 [ 2 68 75 80 83 97]
 [ 3 45 63 65 98 99]
 [ 4 59 65 68 89 93]
 [ 5 49 55 63 70 83]
 [ 6 39 50 78 85 91]]


In [4]:
# Student With Score Higher than 85
m = scores>85
print(scores[m])

# Standard Deviation
std_per_subject = np.std(scores,axis=0)
print("Standard Deviation: ",std_per_subject)

std_per_student = np.std(scores,axis=1)
print("Standard Deviation: ",std_per_student)

[95 99 93 97 99 98 89 93 91]
Standard Deviation:  [ 1.70782513 19.88857852 23.45503973 13.43812983 10.43498389 13.16561177]
Standard Deviation:  [33.87435936 30.58730674 32.77405817 29.16047553 24.51133525 29.8519495 ]


In [5]:
print("Unsorted Score:",scores)
print("Sorted Score: ",np.sort(scores))


Unsorted Score: [[ 1 95 99 85 78 93]
 [ 2 97 80 75 68 83]
 [ 3 45 99 65 98 63]
 [ 4 65 59 89 68 93]
 [ 5 55 49 83 70 63]
 [ 6 85 39 50 78 91]]
Sorted Score:  [[ 1 78 85 93 95 99]
 [ 2 68 75 80 83 97]
 [ 3 45 63 65 98 99]
 [ 4 59 65 68 89 93]
 [ 5 49 55 63 70 83]
 [ 6 39 50 78 85 91]]


In [6]:
print("Shape: ",scores.shape)
print("Dimension:",scores.ndim)
print("Size: ",scores.size)
print("Data type: ",scores.dtype)


Shape:  (6, 6)
Dimension: 2
Size:  36
Data type:  int64


In [7]:
ravel_score = scores.ravel()
print("\n Ravel Score Array : ",ravel_score)

flattend_score = scores.flatten()
print("\n Flatttend score Array: ",flattend_score)

transpose_score = scores.T
print("\n Transposed Score Array: ",transpose_score)


 Ravel Score Array :  [ 1 95 99 85 78 93  2 97 80 75 68 83  3 45 99 65 98 63  4 65 59 89 68 93
  5 55 49 83 70 63  6 85 39 50 78 91]

 Flatttend score Array:  [ 1 95 99 85 78 93  2 97 80 75 68 83  3 45 99 65 98 63  4 65 59 89 68 93
  5 55 49 83 70 63  6 85 39 50 78 91]

 Transposed Score Array:  [[ 1  2  3  4  5  6]
 [95 97 45 65 55 85]
 [99 80 99 59 49 39]
 [85 75 65 89 83 50]
 [78 68 98 68 70 78]
 [93 83 63 93 63 91]]
